Document: nx-misc-utils
Title: Debian nx-misc-utils Manual
Author: <insert document author here>
Abstract: This manual describes what nx-misc-utils is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/nx-misc-utils/nx-misc-utils.sgml.gz

Format: postscript
Files: /usr/share/doc/nx-misc-utils/nx-misc-utils.ps.gz

Format: text
Files: /usr/share/doc/nx-misc-utils/nx-misc-utils.text.gz

Format: HTML
Index: /usr/share/doc/nx-misc-utils/html/index.html
Files: /usr/share/doc/nx-misc-utils/html/*.html
